name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and attach to release
        uses: BigWigsMods/packager@master
        with:
          # -d: kein Upload zu CurseForge/WoWInterface/Wago
          args: -d
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
